name: Update mihomo binaries

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest release
      id: get-release
      run: |
        LATEST_TAG=$(curl -sL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Check existing version
      id: check-version
      run: |
        if [ -f "MerlinClash2/version.txt" ]; then
          CURRENT_VERSION=$(cat MerlinClash2/version.txt)
          if [ "$CURRENT_VERSION" == "${{ steps.get-release.outputs.latest_tag }}" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        echo "skip=false" >> $GITHUB_OUTPUT

    - name: Exit if no update needed
      if: steps.check-version.outputs.skip == 'true'
      run: exit 0

    - name: Setup environment
      run: |
        TAG_NAME=${{ steps.get-release.outputs.latest_tag }}
        wget "https://github.com/MetaCubeX/mihomo/archive/refs/tags/${TAG_NAME}.tar.gz"
        tar -xzf "${TAG_NAME}.tar.gz"
        DIR_NAME=$(tar -tzf "${TAG_NAME}.tar.gz" | head -1 | cut -f1 -d"/")
        echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV
        rm "${TAG_NAME}.tar.gz"

    - name: Modify build configuration
      run: |
        cd $DIR_NAME
        sed -i 's/-tags with_gvisor//' Makefile

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y upx

    - name: Build ARM binaries
      run: |
        cd $DIR_NAME
        make linux-armv7 linux-arm64

    - name: Compress and rename binaries
      run: |
        cd $DIR_NAME/bin
        mkdir -p ../../MerlinClash2/{bin32,bin64}
        
        # ARMv7 重命名为 clash 并放入 bin32
        upx --lzma mihomo-linux-armv7 -o ../../MerlinClash2/bin32/clash
        # ARM64 重命名为 clash 并放入 bin64
        upx --lzma mihomo-linux-arm64 -o ../../MerlinClash2/bin64/clash

        # 验证文件
        ls -la ../../MerlinClash2/bin32/clash
        ls -la ../../MerlinClash2/bin64/clash

    - name: Update version record
      run: |
        echo "${{ steps.get-release.outputs.latest_tag }}" > MerlinClash2/version.txt

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add MerlinClash2/
        git commit -m "chore: Update mihomo to ${{ steps.get-release.outputs.latest_tag }}"
        git push
