name: Auto Build Mihomo

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC午夜检查
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check current repo
      uses: actions/checkout@v4

    - name: Get latest MetaCubeX release
      id: meta-release
      run: |
        LATEST_TAG=$(curl -sL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
        echo "META_VERSION=${LATEST_TAG}" >> $GITHUB_ENV

    - name: Get latest self release
      id: self-release
      run: |
        SELF_TAG=$(curl -sL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name // ""')
        echo "SELF_VERSION=${SELF_TAG}" >> $GITHUB_ENV

    - name: Compare versions
      id: compare
      run: |
        if [ "${{ env.SELF_VERSION }}" = "${{ env.META_VERSION }}" ]; then
          echo "No new version available"
          echo "SKIP=true" >> $GITHUB_ENV
        else
          echo "New version detected"
          echo "SKIP=false" >> $GITHUB_ENV
        fi

    - name: Exit if no update
      if: env.SKIP == 'true'
      run: exit 0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install UPX
      run: |
        sudo apt-get update
        sudo apt-get install -y upx

    - name: Download source
      run: |
        wget https://github.com/MetaCubeX/mihomo/archive/refs/tags/${{ env.META_VERSION }}.tar.gz
        tar -xzf ${{ env.META_VERSION }}.tar.gz
        mv mihomo-${META_VERSION#v} source

    - name: Build binaries
      strategy:
        matrix:
          include:
            - arch: armv7
              goarch: arm
              goarm: 7
              tags: "with_gvisor"
              suffix: "gvisor"
            - arch: armv7
              goarch: arm
              goarm: 7
              tags: ""
              suffix: ""
            - arch: arm64
              goarch: arm64
              goarm: ""
              tags: "with_gvisor"
              suffix: "gvisor"
            - arch: arm64
              goarch: arm64
              goarm: ""
              tags: ""
              suffix: ""
      env:
        GOOS: linux
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
      run: |
        cd source
        BUILDTIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        FILENAME="mihomo-linux-${{ matrix.arch }}"
        [[ -n "${{ matrix.suffix }}" ]] && FILENAME="${FILENAME}-${{ matrix.suffix }}"        
        CGO_ENABLED=0 go build \
          -tags "${{ matrix.tags }}" \
          -trimpath \
          -ldflags "-X 'github.com/metacubex/mihomo/constant.Version=${{ env.META_VERSION }}' \
                    -X 'github.com/metacubex/mihomo/constant.BuildTime=$BUILDTIME' \
                    -w -s -buildid=linux-${{ matrix.arch }}" \
          -o ../$FILENAME
        
        cd ..
        upx --lzma $FILENAME

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.META_VERSION }}
        name: "Build for ${{ env.META_VERSION }}"
        body: "Automated build of MetaCubeX/mihomo ${{ env.META_VERSION }}"
        files: |
          mihomo-linux-*
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
